--ELIMINE AL ALUMNO (O LOS ALUMNOS) QUE NO TIENE NINGUN CURSO MATRICULADO
--  1)  PRIMERO REVISAMOS LOS ALUMNOS QUE NO ESTEN MATRICULADOS EN NINGUN CURSO.
--      SE VA A CUMPLIR QUE ESTOS ALUMNOS NO TENGAN NINGUNA TUPLA RELACIONADA EN ENROLLMENT

SELECT * FROM STUDENT WHERE STUDENT_ID NOT IN (SELECT STUDENT_ID FROM ENROLLMENT);

--  2)  SABIENDO LOS REGISTROS QUE VAMOS A ELIMINAR PROCEDEMOS CON LA SENTENCIA DELETE
DELETE FROM STUDENT WHERE STUDENT_ID NOT IN (SELECT STUDENT_ID FROM ENROLLMENT);

--ELIMINE A TODOS LOS DOCENTES DEL SISTEMA
--  1)  OBSERVE QUE LOS DOCENTES TIENEN SECCIONES ASOCIADAS, EL SISTEMA NO ME PERMITIRA ELIMINARLOS
--      TRUNCATE TABLE INSTRUCTOR; (VA A FALLAR)
--      PARA REALIZAR LA ELIMINACION PRIMERO DEBEMOS ELIMINAR TODAS LAS SECCIONES QUE TIENEN A CARGO
--      ADEMAS, PARA PODER ELIMINAR LAS SECCIONES DEBO ELIMINAR TODOS LOS REGISTROS DE MATRICULA

TRUNCATE TABLE ENROLLMENT;
TRUNCATE TABLE SECTION;
        
--  2)  UNA VEZ ELIMINADOS ESTOS REGISTROS, PUEDO PROCEDER A ELIMINAR LOS REGISTROS DE DOCENTES
TRUNCATE TABLE INSTRUCTOR;

-- GRACIAS AL SCRIPT QUE HEMOS CREADO, PODEMOS EJECUTARLO Y RESTAURAR LOS DATOS ORIGINALES