SELECT  S.FIRST_NAME, 
        S.LAST_NAME,
        S.PHONE
FROM STUDENT S, ZIPCODE Z
WHERE S.ZIP = Z.ZIP             -- JOIN ENTRE LAS TABLAS
AND Z.CITY = 'LOS ANGELES'      -- CIUDAD DEBE SER LOS ANGELES
AND S.LAST_NAME LIKE '%R%';     -- NOMBRE DEBE CONTENER "R"

