SELECT  I.FIRST_NAME, 
        I.LAST_NAME, 
        COUNT(*) AS SECTIONS                --CANTIDAD DE SECCIONES POR DOCENTE
FROM    INSTRUCTOR I, SECTION S             --DEBO REVISAR INSTRUCTORES POR SECCION
WHERE   I.INSTRUCTOR_ID = S.INSTRUCTOR_ID   --CONDICION DE JOIN    
GROUP BY I.FIRST_NAME, I.LAST_NAME          --AGRUPAMOS POR DOCENTE
HAVING COUNT(*) > 1;                        --DOCENTES CON MAS DE UNA SECCION

