--SE MUESTRA COMO EJEMPLO LA BOLETA DE MATRICULA DEL ALUMNO 100
SELECT  S.FIRST_NAME, 
        S.LAST_NAME,
        C.DESCRIPTION,
        SE.SECTION_NO,
        --MOSTRAMOS NOMBRE COMPLETO DEL DOCENTE
        NVL(I.SALUTATION, '') || I.FIRST_NAME || ' ' || I.LAST_NAME AS INST
FROM    STUDENT S,
        ENROLLMENT E,
        SECTION SE,
        --NO SE MENCIONA DIRECTAMENTE PERO NECESITAMOS EL NOMBRE DEL CURSO
        COURSE C,
        INSTRUCTOR I
--USAMOS LAS RELACIONES ENTRE LAS TABLAS PARA PLANTEAR LAS CONDICIONES DEL JOIN
WHERE   E.STUDENT_ID = S.STUDENT_ID
AND     E.SECTION_ID = SE.SECTION_ID
AND     SE.INSTRUCTOR_ID = I.INSTRUCTOR_ID
AND     SE.COURSE_NO = C.COURSE_NO
AND     S.STUDENT_ID = 100;     --LA IDEA ES MOSTRARLO PARA UN ALUMNO



