/*
ALGUNOS TEMAS IMPORTANTES
-   PUEDO ENCONTRAR LA CAPACIDAD DE LA SECCION EN EL ATRIBUTO CAPACITY (TABLA SECTION)
-   PARA SABER LA CANTIDAD DE ALUMNOS MATRICULADOS EN LA SECCION PUEDO USAR LA TABLA ENROLLMENT
    POR EJEMPLO, PARA SABER CUANTOS ALUMNOS ESTAN MATRICULADOS EN LA SECCION 1005:
    SELECT COUNT(*) FROM ENROLLMENT WHERE SECTION_ID = 1005;
-   CON ELLO, LOS LUGARES DISPONIBLES SERAN LA DIFERENCIA DE LOS 2 NUMEROS ANTERIORES.
    UTILIZAREMOS ESTOS CRITERIOS EN NUESTRA SOLUCION
*/

SELECT  C.COURSE_NO,
        C.DESCRIPTION,
        SE.SECTION_NO,
        I.FIRST_NAME || ' '  || I.LAST_NAME AS INST,
        SE.CAPACITY,
        --LA DISPONIBILIDAD ES LA CAPACIDAD MENOS EL CONTEO DE MATRICULADOS
        SE.CAPACITY - (SELECT COUNT(*) FROM ENROLLMENT WHERE SECTION_ID = SE.SECTION_ID) AS DISP
FROM    SECTION SE,
        COURSE C,
        INSTRUCTOR I
WHERE   SE.COURSE_NO = C.COURSE_NO
AND     SE.INSTRUCTOR_ID = I.INSTRUCTOR_ID;

