--UNA FORMA DIRECTA DE DE OBTENER LA RESPUESTA ES HALLANDO PRIMERAMENTE EL CONTEO POR CURSO
--PODEMOS HACERLO CON ESTA CONSULTA:

SELECT  C.COURSE_NO, 
        C.DESCRIPTION, 
        COUNT(*)
FROM    COURSE C,
        SECTION SE,
        ENROLLMENT E
WHERE   E.SECTION_ID = SE.SECTION_ID
AND     SE.COURSE_NO = C.COURSE_NO
GROUP BY C.COURSE_NO, C.DESCRIPTION;

--PODRIAMOS REALIZAR UNA CLAUSULA HAVING PARA FILTRAR.
--SIN EMBARGO, NO TENEMOS EL PROMEDIO DE LAS CANTIDADES.
--PODEMOS HALLARLO CON UNA CONSULTA MUY SIMILAR
SELECT  AVG(COUNT(*))
FROM    COURSE C,
        SECTION SE,
        ENROLLMENT E
WHERE   E.SECTION_ID = SE.SECTION_ID
AND     SE.COURSE_NO = C.COURSE_NO
GROUP BY C.COURSE_NO, C.DESCRIPTION;

--PODEMOS ENTONCES COMBINAR AMBAS CONSULTAS.
--AGREGAMOS UNA CLAUSULA HACING CON EL RESULTADO DE LA SEGUNDA CONSULTA
--CON ELLO OBTENEMOS LAS RESPUESTA

SELECT  C.COURSE_NO, 
        C.DESCRIPTION,
        COUNT(*)
FROM    COURSE C,
        SECTION SE,
        ENROLLMENT E
WHERE   E.SECTION_ID = SE.SECTION_ID
AND     SE.COURSE_NO = C.COURSE_NO
GROUP BY C.COURSE_NO, C.DESCRIPTION
HAVING COUNT(*) > ( SELECT AVG(COUNT(*))
                    FROM    COURSE C,
                            SECTION SE,
                            ENROLLMENT E
                    WHERE   E.SECTION_ID = SE.SECTION_ID
                    AND     SE.COURSE_NO = C.COURSE_NO
                    GROUP BY C.COURSE_NO, C.DESCRIPTION
                  );
