--FUNCTION
CREATE OR REPLACE FUNCTION CALCULAR_IGV(monto NUMBER)
RETURN NUMBER AS
    igv NUMBER;
    PORC_IGV CONSTANT NUMBER := 0.18;
BEGIN
    igv := monto * PORC_IGV;
    RETURN igv;
END;

--PROCEDURE
CREATE OR REPLACE PROCEDURE REGISTRAR_PRODUCTO( nombre PRODUCTO1.NOMBRE%TYPE,
                                                precio PRODUCTO1.PRECIO_UNITARIO%TYPE)
AS
codigo PRODUCTO1.CODIGO%TYPE;
BEGIN
    SELECT NVL(MAX(CODIGO), 0) + 1
    INTO codigo
    FROM PRODUCTO1;

    INSERT INTO PRODUCTO1 VALUES(codigo, nombre, precio);
END;
