--1)

--A)
CREATE TABLE PAIS(
CODIGO INTEGER PRIMARY KEY,
NOMBRE VARCHAR2(50),
POBLACION INTEGER);

CREATE TABLE ESPECIALIDAD(
CODIGO INTEGER PRIMARY KEY,
NOMBRE VARCHAR2(50)
);

CREATE TABLE MEDICO(
DNI VARCHAR2(8) PRIMARY KEY,
NOMBRE VARCHAR2(50),
FECHA_NACIMIENTO DATE,
COD_PAIS_RESIDENCIA REFERENCES PAIS,
COD_ESPECIALIDAD REFERENCES ESPECIALIDAD
);

INSERT INTO PAIS VALUES(1, 'PERU', 33);
INSERT INTO PAIS VALUES(2, 'URUGUAY', 4);
INSERT INTO PAIS VALUES(3, 'EEUU', 328);
INSERT INTO PAIS VALUES(4, 'ARGENTINA', 44);


INSERT INTO ESPECIALIDAD VALUES(1, 'CARDIOLOGIA');
INSERT INTO ESPECIALIDAD VALUES(2, 'PEDIATRIA');
INSERT INTO ESPECIALIDAD VALUES(3, 'GERIATRIA');

INSERT INTO MEDICO VALUES('39458394', 'MANUEL VARGAS', TO_DATE('20/11/1990', 'DD/MM/YYYY'), 1, 1);
INSERT INTO MEDICO VALUES('64747489', 'MARIANA CESPEDES', TO_DATE('21/10/1982', 'DD/MM/YYYY'), 2, 2);
INSERT INTO MEDICO VALUES('73485859', 'CESAR PANTA', TO_DATE('11/03/1988', 'DD/MM/YYYY'), 2, 1);


--B)
SELECT M.NOMBRE, TO_CHAR(M.FECHA_NACIMIENTO, 'DD/MM/YYYY'), E.NOMBRE, P.NOMBRE
FROM MEDICO M, ESPECIALIDAD E, PAIS P
WHERE M.COD_PAIS_RESIDENCIA = P.CODIGO
AND M.COD_ESPECIALIDAD = E.CODIGO;

--C)
SELECT E.NOMBRE, COUNT(*)
FROM MEDICO M, ESPECIALIDAD E
WHERE M.COD_ESPECIALIDAD = E.CODIGO
GROUP BY E.NOMBRE;

--D)
SELECT M.DNI, M.NOMBRE, E.NOMBRE
FROM MEDICO M, ESPECIALIDAD E, PAIS P
WHERE M.COD_PAIS_RESIDENCIA = P.CODIGO
AND M.COD_ESPECIALIDAD = E.CODIGO
AND P.POBLACION > = 20
AND EXTRACT(YEAR FROM M.FECHA_NACIMIENTO) >= 1989;

--E)
DELETE FROM MEDICO
WHERE COD_PAIS_RESIDENCIA IN (SELECT CODIGO FROM PAIS WHERE POBLACION < 10);


--2)
SELECT  E.FIRST_NAME, E.LAST_NAME, E.SALARY
FROM    EMPLOYEES E, 
        DEPARTMENTS  D, 
        LOCATIONS L, 
        COUNTRIES C,
        (SELECT JOB_ID, AVG(SALARY) SAL FROM EMPLOYEES GROUP BY JOB_ID) J
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
AND L.LOCATION_ID = D.LOCATION_ID
AND C.COUNTRY_ID = L.COUNTRY_ID
AND E.JOB_ID = J.JOB_ID
AND E.SALARY < 2 * J.SAL
AND E.SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES);

--3)
SELECT  C.COUNTRY_NAME, 
        R.REGION_NAME, 
        COUNT(E.EMPLOYEE_ID), 
        MAX(E.SALARY), 
        MIN(E.SALARY), 
        TRUNC(AVG(E.SALARY), 2),
        TRUNC(100 * NVL(AVG(E.COMMISSION_PCT), 0), 2) || '%'
FROM    EMPLOYEES E, 
        DEPARTMENTS  D, 
        LOCATIONS L, 
        COUNTRIES C,
        REGIONS R
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
AND L.LOCATION_ID = D.LOCATION_ID
AND C.COUNTRY_ID = L.COUNTRY_ID
AND R.REGION_ID = C.REGION_ID
AND D.DEPARTMENT_NAME <> 'Executive'
GROUP BY C.COUNTRY_NAME, R.REGION_NAME
HAVING COUNT(*) > 3;

--4)
SELECT  I.INSTRUCTOR_ID,
        I.FIRST_NAME || ' ' || I.LAST_NAME AS NAME,
        C.DESCRIPTION,
        SE.SECTION_NO,
        SE.LOCATION,
        SE.CAPACITY,
        COUNT(*) AS ENROLLED,
        SE.CAPACITY - COUNT(*) AS AVAILABLE
FROM    INSTRUCTOR I, 
        COURSE C, 
        SECTION SE, 
        ENROLLMENT E, 
        STUDENT S
WHERE I.INSTRUCTOR_ID = SE.INSTRUCTOR_ID
AND C.COURSE_NO = SE.COURSE_NO
AND E.SECTION_ID = SE.SECTION_ID
AND E.STUDENT_ID = S.STUDENT_ID
GROUP BY I.INSTRUCTOR_ID, I.FIRST_NAME, I.LAST_NAME, C.DESCRIPTION, SE.SECTION_NO, SE.LOCATION, SE.CAPACITY;



