--SELECCION
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, PHONE_NUMBER
FROM EMPLOYEES;

--USO DE DISTINCT
SELECT DISTINCT DEPARTMENT_ID FROM EMPLOYEES;

--RELACION RECURSIVA: MANAGER_ID
SELECT * FROM EMPLOYEES
WHERE EMPLOYEE_ID = 101
UNION
SELECT * FROM EMPLOYEES 
WHERE EMPLOYEE_ID = 100;

--CONCATENACION
SELECT FIRST_NAME || ' ' || LAST_NAME AS NOMBRE_COMPLETO 
FROM EMPLOYEES;

SELECT LAST_NAME || ' gana ' || SALARY AS "TEXTO DE PRUEBA"
FROM EMPLOYEES;

--EMPLEADOS CON SALARIO EN EL INTERVALO [4000, 8000>
SELECT * FROM EMPLOYEES
WHERE SALARY >= 4000
AND SALARY < 8000;

--EMPLEADOS CON SALARIO EN EL INTERVALO [10000, 15000]
SELECT * FROM EMPLOYEES
WHERE SALARY BETWEEN 10000 AND 15000;

--EMPLEADOS QUE NO PERTENEZCAN AL DEPARTAMENTO 50
SELECT * FROM EMPLOYEES
WHERE DEPARTMENT_ID <> 50;

--EMPLEADOS QUE GANAN COMISION
SELECT * FROM EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL;

--MUESTRE AQUELLOS EMPLEADOS QUE TRABAJAN EN LOS DEPARTAMENTOS 40 Y 60
SELECT * FROM EMPLOYEES
WHERE DEPARTMENT_ID = 40
OR DEPARTMENT_ID = 60;

--MUESTRE AQUELLOS EMPLEADOS QUE TRABAJAN EN LOS DEPARTAMENTOS 10, 20, 50, 60 Y 70
SELECT * FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (10, 20, 50, 60, 70);

--MUESTRE AQUELLOS EMPLEADOS CUYO APELLIDO EMPIECE CON "J"
SELECT * FROM EMPLOYEES 
WHERE LAST_NAME LIKE 'J%';

--MUESTRE AQUELLOS EMPLEADOS CUYO APELLIDO TERMINO CON "son"
SELECT * FROM EMPLOYEES
WHERE LAST_NAME LIKE '%son';

--MUESTRE LOS EMPLEADOS CUYA SEGUNDA LETRA DEL NOMBRE SEA "o"
SELECT * FROM EMPLOYEES
WHERE FIRST_NAME LIKE '_o%';

--MUESTRE LOS EMPLEADOS CUYA SEGUNDA LETRA DEL NOMBRE SEA "o" Y LA QUINTA "l"
SELECT * FROM EMPLOYEES
WHERE FIRST_NAME LIKE '_o__l%';

--MUESTRE EL NOMBRE COMPLETO DEL EMPLEADO EN MAYUSCULAS
SELECT UPPER(FIRST_NAME || ' ' || LAST_NAME) AS FULL_NAME
FROM EMPLOYEES;

--MUESTRE EL NOMBRE COMPLETO DEL EMPLEADO EN MINUSCULAS
SELECT LOWER(FIRST_NAME || ' ' || LAST_NAME) AS FULL_NAME
FROM EMPLOYEES;

--EMPLEADOS CUYO APELLIDO TENGA MAS DE 8 LETRAS
SELECT *
FROM EMPLOYEES
WHERE LENGTH(LAST_NAME) > 8;

--MUESTRE EL CODIGO DE EMPLEADO CON 8 DIGITOS COMPLETADOS CON CERO A LA IZQUIERDA
SELECT LPAD(EMPLOYEE_ID, 6, '0')
FROM EMPLOYEES;

--MUESTRE EL NOMBRE Y APELLIDO DEL EMPLEADO ALINEADO HACIA LA DERECHA.
--COMPLETE CON ESPACIOS CADA DATO HASTA LOS 20 CARACTERES
SELECT LPAD(FIRST_NAME, 20, ' '), LPAD(LAST_NAME, 20, ' ')
FROM EMPLOYEES;

--MUESTRE EL NOMBRE Y APELLIDO DEL EMPLEADO ALINEADO HACIA LA IZQUIERDA.
--COMPLETE CON ESPACIOS CADA DATO HASTA LOS 20 CARACTERES
SELECT RPAD(FIRST_NAME, 20, ' '), RPAD(LAST_NAME, 20, ' ')
FROM EMPLOYEES;


--ROUND Y TRUNC
SELECT ROUND(12.76), ROUND(12.76, 1), TRUNC(12.76), TRUNC(12.76, 1)
FROM DUAL;


--MUESTRE EL SALARIO MENSUAL DEL EMPLEADO REDONDEADO
SELECT LAST_NAME, SALARY / 12, ROUND(SALARY / 12)
FROM EMPLOYEES;

--MUESTRE EL SALARIO MENSUAL DEL EMPLEADO TRUNCADO A 2 DECIMALES
SELECT LAST_NAME,  SALARY / 12, TRUNC(SALARY / 12, 2)
FROM EMPLOYEES;

--FUNCIONES DE FECHA

--VIAUSLIZACION DE FECHAS

SELECT TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI:SS') FROM DUAL;

SELECT TO_CHAR(HIRE_DATE, 'DD/MM/YYYY') HIRE_DATE FROM EMPLOYEES;

SELECT TO_CHAR(HIRE_DATE, 'YEAR') HIRE_DATE FROM EMPLOYEES;

SELECT TO_CHAR(SYSDATE, 'MONTH, YEAR') HIRE_DATE FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'DAY DD MONTH, YYYY') HIRE_DATE FROM DUAL;

--OBTENGA LA CANTIDAD DE DIAS QUE HAN PASADO DESDE LA CONTRATACION DE CADA
--EMPLEADO

SELECT SYSDATE, HIRE_DATE, TRUNC(SYSDATE - HIRE_DATE)
FROM EMPLOYEES
ORDER BY HIRE_DATE DESC;

--MUESTRE LA CANTIDAD DE MESES QUE HAN TRANSCURRIDO DESDE LA CONTRTACION DEL
--EMPLEADO
SELECT SYSDATE, HIRE_DATE, TRUNC(MONTHS_BETWEEN(SYSDATE, HIRE_DATE))
FROM EMPLOYEES
ORDER BY HIRE_DATE DESC;

SELECT TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI:SS') FROM DUAL;
SELECT TO_CHAR(TRUNC(SYSDATE), 'DD/MM/YYYY HH24:MI:SS') FROM DUAL;

SELECT EXTRACT(YEAR FROM SYSDATE) + 2 FROM DUAL;
SELECT EXTRACT(MONTH FROM SYSDATE) + 2 FROM DUAL; 
SELECT EXTRACT(DAY FROM SYSDATE) + 2 FROM DUAL; 


--HACER UN REPORTE QUE INCLUYA EL NOMBRE DEL EMPLEADO Y EL DEPARTAMENTO
--AL QUE PERTENECE. CONSIDERE TAMBIEN AQUELLOS EMPLEADOS NO ASOCIADOS A NINGUN
--DEPARTAMENTO

--OUTER JOIN

SELECT E.FIRST_NAME, E.LAST_NAME, D.DEPARTMENT_NAME
FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID(+);


--FUNCIONES DE GRUPO

--CANTIDAD DE REGISTROS
SELECT COUNT(*) FROM EMPLOYEES;

--MAXIMO, MINIMO, SUMA Y PROMEDIO
SELECT MAX(SALARY), MIN(SALARY), SUM(SALARY), TRUNC(AVG(SALARY), 2) 
FROM EMPLOYEES;

--ESTADISTICAS POR DEPARTAMENTO
SELECT D.DEPARTMENT_NAME,
COUNT(*),
MAX(SALARY), 
MIN(SALARY),
SUM(SALARY), 
TRUNC(AVG(SALARY), 2) AS AVG_SALARY
FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_NAME
ORDER BY SUM(SALARY) DESC;


--CONSIDERANDO VALORES NULOS
SELECT NVL(D.DEPARTMENT_NAME, 'Contractor'), TRUNC(AVG(SALARY), 2)
FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID(+)
GROUP BY D.DEPARTMENT_NAME
ORDER BY AVG(SALARY) DESC;

-- MUESTRE ESTADISTICAS POR CADA ROL (JOB) - MUESTRE EL CODIGO Y NOMBRE DE ROL.
-- CONSIDERE CANTIDAD DE EMPLEADOS Y PROMEDIO DE SALARIO DE AQUELLOS EMPLEADOS 
-- QUE HAYAN SIDO CONTRATADOS A PARTIR DE 1990.
-- CONSIDERE SOLO AQUELLOS ROLES CON MAS DE 3 EMPLEADOS.

SELECT J.JOB_ID, J.JOB_TITLE, COUNT(*), TRUNC(AVG(SALARY), 2)
FROM EMPLOYEES E, JOBS J
WHERE E.JOB_ID = J.JOB_ID
AND E.HIRE_DATE >= TO_DATE('01/01/1990', 'DD/MM/YYYY')
GROUP BY J.JOB_ID, J.JOB_TITLE
HAVING COUNT(*) > 3;

--IMPLEMENTE UNA CONSULTA QUE MUESTRE LOS DATOS DE AQUELLOS EMPLEADOS
--QUE GANAN MAS QUE EL SALARIO PROMEDIO DE LA EMPRESA

SELECT * FROM EMPLOYEES WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES);

